/* ============================================
   HIREX — Jobs Data (37 mock listings)
   ============================================ */

const JOBS_DATA = [
  {
    id:"job-001",title:"Senior Frontend Engineer",
    company:{name:"Stripe",color:"#635BFF",initials:"ST",size:"1,000–5,000",industry:"Fintech",website:"stripe.com",description:"Stripe builds economic infrastructure for the internet. Millions of businesses use Stripe to accept payments online."},
    location:"San Francisco, CA",remote:"hybrid",type:"full-time",level:"senior",category:"Engineering",
    salary:{min:160000,max:220000},posted:"2026-06-28",featured:true,
    excerpt:"Build the next generation of financial infrastructure using React, TypeScript, and modern web technologies.",
    description:"We're looking for a Senior Frontend Engineer to join our team and help build the next generation of financial infrastructure. You'll work on complex, high-impact projects that touch millions of businesses worldwide.",
    responsibilities:["Build and maintain high-performance React applications used by millions of businesses","Collaborate closely with design, product, and backend teams","Lead technical decision-making for frontend architecture","Improve build tooling, CI/CD pipelines, and developer experience","Mentor junior engineers and conduct code reviews","Drive web performance and accessibility initiatives"],
    requirements:["5+ years of frontend development experience","Expert knowledge of React and TypeScript","Deep understanding of browser internals and web performance","Experience with GraphQL or REST APIs","Strong product sense and attention to design detail","Experience with testing frameworks (Jest, Cypress)"],
    nice_to_have:["Experience with payments or financial products","Knowledge of WebSockets","Open source contributions","React Native experience"],
    skills:["React","TypeScript","GraphQL","Next.js","CSS","Jest"],
    benefits:["Equity","Health insurance","401k matching","$3k learning budget/yr","Remote-friendly","Unlimited PTO"],
    screening_questions:[{id:"q1",question:"Describe the most complex UI component you've built and the challenges you faced.",type:"textarea"},{id:"q2",question:"How many years of React experience do you have?",type:"select",options:["1-2 years","3-4 years","5+ years"]}]
  },
  {
    id:"job-002",title:"Staff Software Engineer",
    company:{name:"Google",color:"#4285F4",initials:"G",size:"100,000+",industry:"Technology",website:"google.com",description:"Google's mission is to organize the world's information and make it universally accessible and useful."},
    location:"Mountain View, CA",remote:"onsite",type:"full-time",level:"lead",category:"Engineering",
    salary:{min:200000,max:280000},posted:"2026-06-25",featured:true,
    excerpt:"Lead technical direction for Google's core search infrastructure, working on systems that serve billions of users.",
    description:"As a Staff Software Engineer at Google, you'll lead technical direction for critical infrastructure, driving architectural decisions that affect billions of users worldwide.",
    responsibilities:["Drive technical strategy and architecture across multiple product areas","Design, build, and maintain scalable distributed systems","Lead cross-functional initiatives and mentor senior engineers","Establish engineering best practices and technical standards","Partner with product managers and executives on roadmap"],
    requirements:["8+ years of software engineering experience","Expertise in distributed systems and large-scale infrastructure","Strong algorithmic problem-solving skills","Experience leading teams and technical initiatives","Proficiency in Java, Go, or C++","Track record of delivering high-impact projects"],
    nice_to_have:["PhD in Computer Science","Experience with ML/AI systems","Publications in top-tier CS venues","Open source project leadership"],
    skills:["Java","Go","Distributed Systems","Kubernetes","BigQuery","gRPC"],
    benefits:["RSUs","Full health/dental/vision","Free meals","Fitness center","$10k learning budget","Parental leave"],
    screening_questions:[{id:"q1",question:"Describe a large-scale system you designed. What were the key trade-offs?",type:"textarea"},{id:"q2",question:"What is your experience level with distributed systems?",type:"select",options:["3-5 years","5-8 years","8+ years"]}]
  },
  {
    id:"job-003",title:"Senior Backend Engineer",
    company:{name:"Netflix",color:"#E50914",initials:"NF",size:"10,000+",industry:"Entertainment",website:"netflix.com",description:"Netflix is the world's leading streaming entertainment service with 260M+ paid memberships globally."},
    location:"Remote",remote:"remote",type:"full-time",level:"senior",category:"Engineering",
    salary:{min:180000,max:250000},posted:"2026-06-26",featured:true,
    excerpt:"Build highly resilient microservices that power Netflix's streaming platform for 260M+ subscribers worldwide.",
    description:"Join Netflix's backend engineering team to build the resilient, highly-available services that power one of the world's largest streaming platforms at massive scale.",
    responsibilities:["Design and build microservices handling millions of requests per second","Implement resilience patterns (circuit breakers, bulkheads, timeouts)","Optimize system performance and reduce latency at scale","Collaborate with cross-functional teams on technical design","Contribute to Netflix OSS and internal platform libraries"],
    requirements:["5+ years of backend engineering experience","Strong knowledge of Java, Kotlin, or Python","Experience building distributed systems at scale","Understanding of microservices architecture","Experience with AWS or GCP","Strong debugging and problem-solving skills"],
    nice_to_have:["Experience with Spring Boot and Netflix OSS","Knowledge of video streaming protocols","Contributions to open-source projects","Experience with Cassandra or DynamoDB"],
    skills:["Java","Kotlin","AWS","Cassandra","Kafka","Docker"],
    benefits:["Top-of-market comp","Unlimited PTO","Remote work","Health insurance","401k","Stock options"],
    screening_questions:[{id:"q1",question:"Describe your experience designing for high availability and fault tolerance.",type:"textarea"},{id:"q2",question:"Which cloud platform are you most experienced with?",type:"select",options:["AWS","GCP","Azure","Multiple"]}]
  },
  {
    id:"job-004",title:"Senior DevOps Engineer",
    company:{name:"GitHub",color:"#6e5494",initials:"GH",size:"3,000–5,000",industry:"Developer Tools",website:"github.com",description:"GitHub is where the world builds software. Millions of developers use GitHub to collaborate and ship code."},
    location:"Remote",remote:"remote",type:"full-time",level:"senior",category:"Engineering",
    salary:{min:150000,max:210000},posted:"2026-06-29",featured:false,
    excerpt:"Manage and scale GitHub's CI/CD infrastructure, enabling millions of developers to ship code with confidence.",
    description:"As a Senior DevOps Engineer at GitHub, you'll build and maintain the infrastructure that powers the world's largest software development platform.",
    responsibilities:["Design and implement CI/CD pipelines","Manage Kubernetes clusters and container orchestration","Improve infrastructure reliability and observability","Automate operational tasks to reduce toil","Lead incident response and post-mortems"],
    requirements:["5+ years of DevOps or SRE experience","Expert knowledge of Kubernetes and Docker","Strong scripting skills (Python, Bash, Go)","Experience with Infrastructure as Code (Terraform, Pulumi)","Experience with monitoring tools (Prometheus, Grafana, Datadog)"],
    nice_to_have:["Contributions to Kubernetes ecosystem","Experience with GitHub Actions","Knowledge of GitOps workflows"],
    skills:["Kubernetes","Terraform","Docker","Go","Prometheus","AWS"],
    benefits:["Remote-first","Equity","Health insurance","$2k home office stipend","Learning budget","Flexible PTO"],
    screening_questions:[{id:"q1",question:"Describe your most complex Kubernetes deployment challenge and how you solved it.",type:"textarea"}]
  },
  {
    id:"job-005",title:"Full Stack Engineer",
    company:{name:"Vercel",color:"#7c3aed",initials:"VC",size:"500–1,000",industry:"Developer Tools",website:"vercel.com",description:"Vercel enables frontend teams to do their best work. They build the platform for frontend developers, with Next.js."},
    location:"Remote",remote:"remote",type:"full-time",level:"mid",category:"Engineering",
    salary:{min:140000,max:200000},posted:"2026-06-30",featured:false,
    excerpt:"Work on Vercel's platform to help millions of developers deploy and scale their Next.js applications globally.",
    description:"Join Vercel's engineering team to build the tools that power modern web development. You'll work on the platform that serves billions of requests globally.",
    responsibilities:["Build new features for Vercel's deployment platform","Work across the stack — Next.js frontend, Node.js backend","Improve developer experience through tooling and APIs","Collaborate with design on polished, high-quality UIs","Participate in on-call rotation"],
    requirements:["3+ years of full-stack development experience","Strong React and Node.js skills","Experience with SQL and NoSQL databases","Understanding of web performance","Familiarity with cloud infrastructure (AWS, GCP)"],
    nice_to_have:["Experience with Edge computing","Open source contributions to React ecosystem","Experience with Rust or Go"],
    skills:["Next.js","React","Node.js","TypeScript","PostgreSQL","Edge"],
    benefits:["Remote-first","Equity","Health insurance","Laptop of choice","Home office budget","Flexible hours"],
    screening_questions:[{id:"q1",question:"What's your experience with Next.js and the Vercel platform?",type:"textarea"}]
  },
  {
    id:"job-006",title:"React Native Engineer",
    company:{name:"Meta",color:"#0082FB",initials:"MT",size:"70,000+",industry:"Social Media",website:"meta.com",description:"Meta builds technologies that help people connect, find communities, and grow businesses across Facebook, Instagram, and WhatsApp."},
    location:"Menlo Park, CA",remote:"hybrid",type:"full-time",level:"mid",category:"Engineering",
    salary:{min:170000,max:230000},posted:"2026-06-27",featured:false,
    excerpt:"Build cross-platform mobile experiences for Facebook, Instagram, and WhatsApp used by 3 billion people.",
    description:"Join Meta's mobile engineering team to build and optimize cross-platform applications for billions of users across Facebook, Instagram, and WhatsApp.",
    responsibilities:["Build features for Meta's React Native mobile apps","Optimize performance for low-end devices","Collaborate with iOS and Android native teams","Implement accessibility features","Write comprehensive unit and integration tests"],
    requirements:["3+ years of React Native experience","Strong JavaScript and TypeScript skills","Understanding of native iOS or Android development","Experience with performance profiling and optimization","Knowledge of state management (Redux, MobX, Zustand)"],
    nice_to_have:["Experience with native module development","Published apps on App Store or Google Play","Knowledge of GraphQL (Relay)"],
    skills:["React Native","TypeScript","Redux","iOS","Android","GraphQL"],
    benefits:["RSUs","Health/dental/vision","Free food on campus","401k","Parental leave","Wellness benefits"],
    screening_questions:[{id:"q1",question:"Describe a performance optimization you implemented in a React Native app.",type:"textarea"}]
  },
  {
    id:"job-007",title:"Product Engineer",
    company:{name:"Linear",color:"#5E6AD2",initials:"LN",size:"50–200",industry:"Productivity",website:"linear.app",description:"Linear is a purpose-built tool for planning and building products. Loved by world-class product teams everywhere."},
    location:"San Francisco, CA",remote:"remote",type:"full-time",level:"mid",category:"Engineering",
    salary:{min:150000,max:215000},posted:"2026-06-28",featured:true,
    excerpt:"Shape the future of software development tooling at one of the fastest-growing productivity startups in the world.",
    description:"At Linear, product engineers work across the full stack to ship polished, high-performance product features with high autonomy and direct impact.",
    responsibilities:["Own features end-to-end from concept to production","Build fast, beautiful UIs using React and custom rendering","Optimize database queries and API performance","Maintain Linear's Electron desktop application","Work autonomously with minimal meetings"],
    requirements:["3+ years of product engineering experience","Strong React and TypeScript skills","Experience with real-time collaborative systems","Good eye for design and UX details","Experience with PostgreSQL and query optimization"],
    nice_to_have:["Experience with CRDTs or OT algorithms","Contributions to developer tools","Experience with Electron"],
    skills:["React","TypeScript","PostgreSQL","GraphQL","Electron","Real-time"],
    benefits:["Competitive equity","Remote-first","Health insurance","Laptop of choice","No meetings culture","Work any timezone"],
    screening_questions:[{id:"q1",question:"What does good software mean to you? Share an example of software you think is excellent.",type:"textarea"}]
  },
  {
    id:"job-008",title:"Machine Learning Engineer",
    company:{name:"Figma",color:"#F24E1E",initials:"FG",size:"1,000–3,000",industry:"Design Tools",website:"figma.com",description:"Figma is a collaborative design platform that helps teams design, prototype, and hand off work together."},
    location:"San Francisco, CA",remote:"hybrid",type:"full-time",level:"senior",category:"Engineering",
    salary:{min:180000,max:260000},posted:"2026-06-24",featured:false,
    excerpt:"Apply ML to transform how designers work — building AI-powered features like auto-layout and design suggestions.",
    description:"Figma's ML team works on applying machine learning to design workflows, creating AI-powered features that make designers more productive.",
    responsibilities:["Develop and deploy ML models for design intelligence features","Build infrastructure for training, serving, and monitoring models","Collaborate with product and design teams on AI feature roadmap","Conduct experiments to improve model performance","Write scalable Python services for model inference"],
    requirements:["4+ years of ML engineering experience","Strong Python and ML framework skills (PyTorch, TensorFlow)","Experience with model deployment and MLOps","Understanding of computer vision or NLP","Experience with cloud ML infrastructure (AWS SageMaker, Vertex AI)"],
    nice_to_have:["Published ML research papers","Experience with generative AI/LLMs","Knowledge of vector databases"],
    skills:["Python","PyTorch","AWS SageMaker","MLOps","Computer Vision","Kubernetes"],
    benefits:["Equity","Health insurance","401k","Design budget","Learning budget","Hybrid work"],
    screening_questions:[{id:"q1",question:"Describe an ML project you built end-to-end. What was the business impact?",type:"textarea"}]
  },
  {
    id:"job-009",title:"Data Engineer",
    company:{name:"Airbnb",color:"#FF5A5F",initials:"AB",size:"5,000–10,000",industry:"Travel & Hospitality",website:"airbnb.com",description:"Airbnb is an online marketplace that connects people who want to rent their homes with people looking for accommodations."},
    location:"San Francisco, CA",remote:"hybrid",type:"full-time",level:"mid",category:"Engineering",
    salary:{min:155000,max:215000},posted:"2026-06-22",featured:false,
    excerpt:"Build and maintain Airbnb's data platform that processes billions of events daily to power product and business decisions.",
    description:"Join Airbnb's data engineering team to build the pipelines, platforms, and tools that enable data-driven decisions across the company.",
    responsibilities:["Design and maintain scalable ETL/ELT data pipelines","Build data models optimized for analytics workloads","Maintain Airflow DAGs and pipeline orchestration","Collaborate with data scientists and analysts","Ensure data quality through monitoring and validation"],
    requirements:["3+ years of data engineering experience","Strong SQL skills and data modeling experience","Experience with Spark or similar distributed compute","Knowledge of Airflow or similar orchestration","Experience with cloud data warehouses (Snowflake, BigQuery)"],
    nice_to_have:["Experience with dbt","Knowledge of streaming platforms (Kafka, Flink)","Experience with data lake architectures"],
    skills:["Python","SQL","Spark","Airflow","Snowflake","dbt"],
    benefits:["Equity (RSUs)","Health insurance","401k","Travel credits","Flexible work","Learning budget"],
    screening_questions:[{id:"q1",question:"Describe the most complex data pipeline you've built. What were the challenges?",type:"textarea"}]
  },
  {
    id:"job-010",title:"Infrastructure Engineer",
    company:{name:"Notion",color:"#6b7280",initials:"NT",size:"500–1,000",industry:"Productivity",website:"notion.so",description:"Notion is an all-in-one workspace for notes, tasks, wikis, and databases used by millions of teams worldwide."},
    location:"San Francisco, CA",remote:"hybrid",type:"full-time",level:"senior",category:"Engineering",
    salary:{min:160000,max:220000},posted:"2026-06-20",featured:false,
    excerpt:"Scale Notion's infrastructure to support rapid growth, improving reliability and performance for millions of users.",
    description:"Join Notion's infrastructure team to build the systems that keep Notion fast, reliable, and scalable for teams worldwide.",
    responsibilities:["Design and implement scalable cloud infrastructure","Manage Kubernetes clusters and container deployments","Build observability systems (metrics, logging, tracing)","Lead database scaling and performance initiatives","Drive incident response and post-mortem culture"],
    requirements:["5+ years of infrastructure or SRE experience","Expert Kubernetes knowledge","Experience with PostgreSQL at scale","Strong Infrastructure as Code skills (Terraform)","Experience with AWS"],
    nice_to_have:["Experience scaling startups through hypergrowth","Knowledge of Rust or Go","Database internals knowledge"],
    skills:["Kubernetes","AWS","PostgreSQL","Terraform","Datadog","Go"],
    benefits:["Equity","Health insurance","Home office stipend","Learning budget","Flexible PTO","Team retreats"],
    screening_questions:[{id:"q1",question:"How have you handled a major infrastructure incident? Walk us through your approach.",type:"textarea"}]
  },
  {
    id:"job-011",title:"Security Engineer",
    company:{name:"Atlassian",color:"#0052CC",initials:"AT",size:"10,000+",industry:"Developer Tools",website:"atlassian.com",description:"Atlassian creates tools like Jira, Confluence, and Trello that help teams plan, track, and ship software."},
    location:"Sydney, Australia",remote:"hybrid",type:"full-time",level:"senior",category:"Engineering",
    salary:{min:140000,max:190000},posted:"2026-06-18",featured:false,
    excerpt:"Protect Atlassian's products and infrastructure, ensuring security for millions of enterprise teams worldwide.",
    description:"Atlassian's security team is looking for a Senior Security Engineer to help protect our products, infrastructure, and customers at scale.",
    responsibilities:["Conduct security assessments and penetration testing","Design and implement security controls and frameworks","Respond to and investigate security incidents","Collaborate with engineering teams on secure-by-design features","Build security automation and tooling"],
    requirements:["5+ years of security engineering experience","Experience with penetration testing and security assessments","Knowledge of cloud security (AWS, GCP, Azure)","Understanding of OWASP Top 10 and common vulnerabilities","Security certifications preferred (OSCP, CISSP)"],
    nice_to_have:["Bug bounty program experience","Knowledge of compliance frameworks (SOC 2, ISO 27001)","Experience with SIEM and security tooling"],
    skills:["Python","AWS Security","Penetration Testing","SIEM","Docker","Terraform"],
    benefits:["Equity","Health insurance","Paid parental leave","Team retreats","$7.5k learning budget/yr","Flexible work"],
    screening_questions:[{id:"q1",question:"Describe a security vulnerability you discovered and how you helped remediate it.",type:"textarea"}]
  },
  {
    id:"job-012",title:"Ruby on Rails Developer",
    company:{name:"Shopify",color:"#96BF48",initials:"SF",size:"10,000+",industry:"E-Commerce",website:"shopify.com",description:"Shopify powers over 1.7 million businesses in 175 countries, providing tools to start, grow, and manage a business."},
    location:"Ottawa, Canada",remote:"hybrid",type:"full-time",level:"mid",category:"Engineering",
    salary:{min:120000,max:175000},posted:"2026-06-15",featured:false,
    excerpt:"Build the commerce platform that powers over 1.7 million merchants worldwide using Ruby on Rails.",
    description:"Join Shopify's engineering team to build the commerce infrastructure that helps entrepreneurs around the world grow their businesses.",
    responsibilities:["Build features for Shopify's core commerce platform","Maintain and improve large-scale Ruby on Rails codebases","Write performant, well-tested code","Collaborate with product managers and designers","Contribute to API design and developer experience"],
    requirements:["3+ years of Ruby on Rails experience","Strong SQL and MySQL/PostgreSQL skills","Understanding of RESTful API design","Experience with testing (RSpec, Minitest)","Experience with job queuing (Sidekiq)"],
    nice_to_have:["Experience with React for frontend features","Knowledge of e-commerce concepts","Open source contributions to Rails ecosystem"],
    skills:["Ruby on Rails","PostgreSQL","Redis","GraphQL","RSpec","Sidekiq"],
    benefits:["Equity","Health benefits","Parental leave","Remote-friendly","Learning budget","Wellness credits"],
    screening_questions:[{id:"q1",question:"What's a complex Rails performance problem you've solved?",type:"textarea"}]
  },
  // DESIGN
  {
    id:"job-013",title:"Senior Product Designer",
    company:{name:"Apple",color:"#555555",initials:"AP",size:"150,000+",industry:"Consumer Electronics",website:"apple.com",description:"Apple creates products that enrich people's lives at the intersection of technology and liberal arts."},
    location:"Cupertino, CA",remote:"onsite",type:"full-time",level:"senior",category:"Design",
    salary:{min:160000,max:225000},posted:"2026-06-28",featured:true,
    excerpt:"Design beautiful, intuitive experiences for Apple's world-class products used by billions of people every day.",
    description:"Apple is looking for a Senior Product Designer to create exceptional experiences that push the boundaries of what's possible in software design.",
    responsibilities:["Design end-to-end experiences for Apple software products","Create high-fidelity prototypes and interaction specifications","Collaborate with engineering to bring designs to life","Conduct user research and usability testing","Maintain and evolve Apple's Human Interface Guidelines"],
    requirements:["6+ years of product design experience","Expert proficiency in Figma and Protopie","Deep understanding of Apple's HIG","Strong visual design and typography skills","Experience with animation and interaction design"],
    nice_to_have:["Experience designing for iOS, macOS, and watchOS","Motion design skills (After Effects)","3D design experience","Understanding of SwiftUI"],
    skills:["Figma","Protopie","Sketch","After Effects","User Research","iOS Design"],
    benefits:["RSUs","Health/dental/vision","Employee discount","401k","Fitness center","Parental leave"],
    screening_questions:[{id:"q1",question:"Walk us through your design process for a recent complex project.",type:"textarea"}]
  },
  {
    id:"job-014",title:"UX Designer",
    company:{name:"Spotify",color:"#1DB954",initials:"SP",size:"5,000–10,000",industry:"Music & Audio",website:"spotify.com",description:"Spotify is a digital music service that gives you access to millions of songs, podcasts, and videos globally."},
    location:"Stockholm, Sweden",remote:"hybrid",type:"full-time",level:"mid",category:"Design",
    salary:{min:95000,max:135000},posted:"2026-06-25",featured:false,
    excerpt:"Design user experiences that connect 600M+ listeners with music they love across all platforms.",
    description:"Join Spotify's design team to create experiences that connect hundreds of millions of users with the music, podcasts, and audiobooks they love.",
    responsibilities:["Design user experiences for Spotify's core listening product","Conduct user research and synthesize findings","Create wireframes, prototypes, and high-fidelity designs","Collaborate with product managers and engineers","Contribute to Spotify's design system (Encore)"],
    requirements:["3+ years of UX/product design experience","Proficiency in Figma","Experience conducting user research","Strong understanding of mobile design patterns","Portfolio of shipped consumer products"],
    nice_to_have:["Passion for music or audio content","Experience with A/B testing design variants","Knowledge of accessibility standards"],
    skills:["Figma","User Research","Prototyping","Mobile Design","Design Systems","Usability Testing"],
    benefits:["Equity","Free Spotify Premium","Health insurance","Parental leave","Flexible work","Learning budget"],
    screening_questions:[{id:"q1",question:"Describe a design decision where you balanced user needs with business constraints.",type:"textarea"}]
  },
  {
    id:"job-015",title:"Design Systems Lead",
    company:{name:"Figma",color:"#F24E1E",initials:"FG",size:"1,000–3,000",industry:"Design Tools",website:"figma.com",description:"Figma is a collaborative design platform that helps teams design, prototype, and hand off work at scale."},
    location:"San Francisco, CA",remote:"hybrid",type:"full-time",level:"lead",category:"Design",
    salary:{min:165000,max:230000},posted:"2026-06-22",featured:false,
    excerpt:"Lead the design systems team at Figma — the company that literally invented the modern design system workflow.",
    description:"Lead Figma's internal design systems team to build and maintain the component library and design language that powers all of Figma's products.",
    responsibilities:["Lead a team of design systems designers and engineers","Define and evolve Figma's design language","Build and maintain component libraries in Figma","Partner with engineering on component API design","Establish governance processes for design system adoption"],
    requirements:["6+ years of design experience with 2+ in design systems","Expert Figma skills","Strong visual design fundamentals","Experience managing design projects at scale","Understanding of frontend implementation (HTML/CSS)"],
    nice_to_have:["Experience with code-side design systems (Storybook, Radix)","Published work on design systems","Token-based theming experience"],
    skills:["Figma","Design Systems","Component Libraries","Design Tokens","Leadership","CSS"],
    benefits:["Equity","Health insurance","$2k learning budget/yr","Hybrid work","Design software budget","Parental leave"],
    screening_questions:[{id:"q1",question:"Describe the most impactful design system you contributed to. What was your role?",type:"textarea"}]
  },
  {
    id:"job-016",title:"Product Designer",
    company:{name:"Notion",color:"#6b7280",initials:"NT",size:"500–1,000",industry:"Productivity",website:"notion.so",description:"Notion is an all-in-one workspace that replaces wikis, docs, and project management tools for millions of teams."},
    location:"San Francisco, CA",remote:"hybrid",type:"full-time",level:"mid",category:"Design",
    salary:{min:140000,max:185000},posted:"2026-06-18",featured:false,
    excerpt:"Design product experiences that help millions of teams organize their work and knowledge effectively.",
    description:"Join Notion's design team to shape the future of how teams work together. You'll own end-to-end design for core product features with high autonomy.",
    responsibilities:["Own design for one or more product areas","Facilitate design sprints and workshops","Create prototypes to test and validate ideas","Collaborate closely with engineering on implementation quality","Contribute to Notion's design system"],
    requirements:["3+ years of product design experience","Proficiency in Figma","Experience with interaction and motion design","Strong systems thinking","Portfolio demonstrating complex product design work"],
    nice_to_have:["Experience designing productivity or collaboration tools","Frontend development skills","Motion design skills"],
    skills:["Figma","Prototyping","Design Systems","User Research","Motion Design","UX Writing"],
    benefits:["Equity","Health insurance","Flexible work","Learning budget","Team offsites","Notion workspace"],
    screening_questions:[{id:"q1",question:"Share a design where you improved a complex workflow. What was the before and after?",type:"textarea"}]
  },
  {
    id:"job-017",title:"Visual Designer",
    company:{name:"Dropbox",color:"#0061FF",initials:"DB",size:"3,000–5,000",industry:"Cloud Storage",website:"dropbox.com",description:"Dropbox helps people and teams keep their files safe, synced, and easy to share from any device, anywhere."},
    location:"Remote",remote:"remote",type:"full-time",level:"mid",category:"Design",
    salary:{min:115000,max:155000},posted:"2026-06-10",featured:false,
    excerpt:"Create stunning visual designs for Dropbox's product and marketing, shaping the visual identity of a beloved brand.",
    description:"Dropbox is looking for a talented Visual Designer to create high-quality visual designs across our product and marketing channels.",
    responsibilities:["Create visual designs for product UI and marketing materials","Develop and maintain brand visual guidelines","Design illustrations, icons, and motion graphics","Collaborate with marketing and product teams","Create assets for web, mobile, and social"],
    requirements:["3+ years of visual design experience","Expert Figma and Adobe Creative Suite skills","Strong illustration and icon design skills","Experience with motion design","Portfolio showing range of visual work"],
    nice_to_have:["Experience with 3D design (Cinema 4D, Blender)","Video editing skills","HTML/CSS knowledge"],
    skills:["Figma","Illustrator","After Effects","Photoshop","Illustration","Motion Design"],
    benefits:["Remote-first","Health insurance","Equity","Learning budget","Flexible PTO","Home office stipend"],
    screening_questions:[{id:"q1",question:"Share a visual design project you're most proud of. What was your creative process?",type:"textarea"}]
  },
  // MARKETING
  {
    id:"job-018",title:"Content Marketing Manager",
    company:{name:"HubSpot",color:"#FF7A59",initials:"HS",size:"7,000+",industry:"Marketing Software",website:"hubspot.com",description:"HubSpot develops and markets software for inbound marketing, sales, and customer service."},
    location:"Boston, MA",remote:"hybrid",type:"full-time",level:"mid",category:"Marketing",
    salary:{min:85000,max:120000},posted:"2026-06-27",featured:false,
    excerpt:"Drive HubSpot's content strategy, creating thought leadership that helps millions of businesses grow better.",
    description:"HubSpot is looking for a Content Marketing Manager to develop and execute content strategy that educates, engages, and converts our global audience.",
    responsibilities:["Develop and execute multi-channel content strategy","Write and edit blog posts, ebooks, whitepapers, and case studies","Manage editorial calendar and content pipeline","Collaborate with SEO team to optimize content","Analyze content performance and optimize based on data"],
    requirements:["4+ years of content marketing experience","Excellent writing and editing skills","Experience with SEO and keyword research","Data-driven approach to content strategy","Experience with CMS and marketing automation"],
    nice_to_have:["Experience with HubSpot marketing tools","Video content production skills","Podcast production experience"],
    skills:["Content Strategy","SEO","HubSpot","Copywriting","Analytics","Email Marketing"],
    benefits:["Health insurance","Stock options","401k","Flexible PTO","Remote-friendly","Learning budget"],
    screening_questions:[{id:"q1",question:"Share a content piece you're proud of. What was the strategy and what results did it achieve?",type:"textarea"}]
  },
  {
    id:"job-019",title:"Product Marketing Manager",
    company:{name:"Salesforce",color:"#00A1E0",initials:"SF",size:"70,000+",industry:"CRM & Cloud",website:"salesforce.com",description:"Salesforce is the world's #1 CRM platform, helping companies connect with customers in new ways."},
    location:"San Francisco, CA",remote:"hybrid",type:"full-time",level:"mid",category:"Marketing",
    salary:{min:110000,max:155000},posted:"2026-06-24",featured:false,
    excerpt:"Drive go-to-market strategy for Salesforce's flagship CRM products used by 150,000+ companies worldwide.",
    description:"Salesforce is seeking a Product Marketing Manager to develop go-to-market strategy, messaging, and positioning for our core CRM products.",
    responsibilities:["Develop product positioning, messaging, and value propositions","Create sales enablement materials and battlecards","Plan and execute product launches","Conduct competitive analysis and win/loss research","Partner with product management on roadmap communication"],
    requirements:["4+ years of product marketing experience","B2B SaaS experience strongly preferred","Strong written and verbal communication","Experience with go-to-market planning","Ability to translate technical features into business value"],
    nice_to_have:["Experience with CRM or enterprise software","MBA from top business school","Analyst relations experience"],
    skills:["Go-to-Market","Positioning","Sales Enablement","Competitive Analysis","Salesforce","Messaging"],
    benefits:["RSUs","Health/dental/vision","401k matching","Wellness reimbursement","Volunteer days","Parental leave"],
    screening_questions:[{id:"q1",question:"Describe a product launch you managed. What was your strategy and what were the results?",type:"textarea"}]
  },
  {
    id:"job-020",title:"Developer Advocate",
    company:{name:"Twilio",color:"#F22F46",initials:"TW",size:"6,000+",industry:"Communications",website:"twilio.com",description:"Twilio powers real-time business communications, allowing developers to build apps with phone calls, texts, and emails."},
    location:"Remote",remote:"remote",type:"full-time",level:"mid",category:"Marketing",
    salary:{min:115000,max:160000},posted:"2026-06-20",featured:false,
    excerpt:"Represent Twilio in the developer community by creating tutorials, speaking at conferences, and building demos.",
    description:"Join Twilio's DevRel team to connect with the global developer community, create educational content, and help developers build amazing things with Twilio.",
    responsibilities:["Create technical tutorials, blog posts, and video content","Speak at conferences and developer meetups","Build demo applications and code samples","Gather developer feedback and share with product teams","Engage with the community on social media and forums"],
    requirements:["3+ years of software development experience","Experience with communications APIs","Strong public speaking and presentation skills","Excellent technical writing skills","Passion for developer education and community"],
    nice_to_have:["YouTube or podcast following","Conference speaking history","Open source project maintenance"],
    skills:["Node.js","Python","Technical Writing","Public Speaking","REST APIs","Community Building"],
    benefits:["Remote-first","Health insurance","Stock options","Conference budget","Learning budget","Home office stipend"],
    screening_questions:[{id:"q1",question:"Share a technical talk, tutorial, or blog post you've created. What was the impact?",type:"textarea"}]
  },
  {
    id:"job-021",title:"Growth Marketing Lead",
    company:{name:"Intercom",color:"#1F8DED",initials:"IC",size:"1,000–3,000",industry:"Customer Messaging",website:"intercom.com",description:"Intercom is the customer messaging platform that helps businesses build better relationships."},
    location:"Dublin, Ireland",remote:"hybrid",type:"full-time",level:"senior",category:"Marketing",
    salary:{min:95000,max:135000},posted:"2026-06-15",featured:false,
    excerpt:"Lead Intercom's growth marketing strategy, running experiments across paid, organic, and product channels.",
    description:"Intercom is looking for a Growth Marketing Lead to run experiments across acquisition channels, optimize funnels, and drive sustainable customer growth.",
    responsibilities:["Develop and execute growth experiments across all channels","Manage paid acquisition campaigns (Google, LinkedIn, Meta)","Optimize conversion funnels from awareness to activation","Analyze data to identify growth opportunities","Lead A/B testing program and maintain experiment backlog"],
    requirements:["5+ years of growth marketing experience","Experience with paid acquisition at scale","Strong analytical skills and SQL proficiency","Experience with attribution modeling","Track record of driving measurable growth"],
    nice_to_have:["Experience with PLG (product-led growth) motions","Knowledge of marketing analytics tools","Experience with international markets"],
    skills:["Growth Marketing","Paid Acquisition","SQL","A/B Testing","Analytics","Attribution"],
    benefits:["Equity","Health insurance","Flexible work","€2k learning budget/yr","Team retreats","Irish pension"],
    screening_questions:[{id:"q1",question:"Describe a growth experiment you ran. What was your hypothesis and what did you learn?",type:"textarea"}]
  },
  {
    id:"job-022",title:"SEO Specialist",
    company:{name:"Mailchimp",color:"#e6a817",initials:"MC",size:"1,000–3,000",industry:"Email Marketing",website:"mailchimp.com",description:"Mailchimp is an all-in-one marketing platform that helps small businesses grow their audience and drive sales."},
    location:"Atlanta, GA",remote:"onsite",type:"full-time",level:"mid",category:"Marketing",
    salary:{min:78000,max:108000},posted:"2026-06-12",featured:false,
    excerpt:"Drive organic traffic growth for Mailchimp through technical SEO, content optimization, and link building.",
    description:"Mailchimp is seeking an SEO Specialist to develop and execute search engine optimization strategies that drive organic growth.",
    responsibilities:["Conduct technical SEO audits and implement recommendations","Perform keyword research and content gap analysis","Optimize existing content for search performance","Build backlinks through digital PR and partnerships","Track and report on organic search KPIs"],
    requirements:["3+ years of SEO experience","Proficiency with SEO tools (Ahrefs, SEMrush, Search Console)","Understanding of technical SEO (crawlability, site speed, schema)","Experience with content optimization","Basic HTML knowledge"],
    nice_to_have:["Experience with large-scale websites","Knowledge of Python for SEO automation","International SEO experience"],
    skills:["Technical SEO","Ahrefs","Google Search Console","Content Optimization","Link Building","Analytics"],
    benefits:["Health insurance","401k","Parental leave","Wellness benefits","Professional development","Flexible PTO"],
    screening_questions:[{id:"q1",question:"Describe an SEO campaign you ran. What was the approach and what results did you achieve?",type:"textarea"}]
  },
  // PRODUCT
  {
    id:"job-023",title:"Senior Product Manager",
    company:{name:"Asana",color:"#FC636B",initials:"AS",size:"1,500+",industry:"Project Management",website:"asana.com",description:"Asana helps teams orchestrate their work, from daily tasks to strategic initiatives, in one platform."},
    location:"San Francisco, CA",remote:"hybrid",type:"full-time",level:"senior",category:"Product",
    salary:{min:150000,max:205000},posted:"2026-06-28",featured:true,
    excerpt:"Lead product strategy for Asana's core work management platform used by teams at 200,000+ companies.",
    description:"Join Asana's product team to define and ship features that help teams around the world achieve their goals and do their best work.",
    responsibilities:["Define product vision, strategy, and roadmap for your product area","Write detailed product specifications and user stories","Work closely with engineering and design on execution","Conduct user research and analyze product metrics","Prioritize features based on impact and customer feedback"],
    requirements:["5+ years of product management experience","Track record of shipping successful B2B SaaS products","Data-driven decision making with strong SQL skills","Excellent communication and stakeholder management","Strong technical background to collaborate with engineering"],
    nice_to_have:["Experience with project management or collaboration tools","MBA from top business school","Engineering background"],
    skills:["Product Strategy","SQL","User Research","Roadmapping","Agile","Stakeholder Management"],
    benefits:["Equity (RSUs)","Health/dental/vision","401k","Wellness benefit","Flexible PTO","Learning budget"],
    screening_questions:[{id:"q1",question:"Tell us about a product you managed from conception to launch. What were the key challenges?",type:"textarea"},{id:"q2",question:"How many years of B2B SaaS PM experience do you have?",type:"select",options:["2-3 years","4-5 years","6+ years"]}]
  },
  {
    id:"job-024",title:"Group Product Manager",
    company:{name:"Slack",color:"#4A154B",initials:"SL",size:"3,000+",industry:"Communication",website:"slack.com",description:"Slack is a messaging platform for teams that brings all your communication together in one place."},
    location:"San Francisco, CA",remote:"hybrid",type:"full-time",level:"lead",category:"Product",
    salary:{min:185000,max:250000},posted:"2026-06-22",featured:false,
    excerpt:"Lead a squad of product managers at Slack to define the future of team communication and collaboration.",
    description:"As a Group Product Manager at Slack, you'll lead multiple product managers, set the direction for a major product area, and define the future of team communication.",
    responsibilities:["Manage and develop a team of 3-4 Product Managers","Define product strategy for a major Slack product area","Partner with engineering leadership on technical strategy","Drive alignment across product, design, and engineering","Develop PM talent through coaching and mentorship"],
    requirements:["7+ years of product management experience","2+ years of PM management experience","Track record of building 0-to-1 and scaling products","Experience with enterprise collaboration tools","Strong data analysis and communication skills"],
    nice_to_have:["Experience with AI/ML product development","Knowledge of enterprise security and compliance","International product expansion experience"],
    skills:["Product Leadership","PM Management","Strategy","Enterprise Products","Communication","Data Analysis"],
    benefits:["Competitive equity","Full benefits","401k","Flexible work","Development budget","Parental leave"],
    screening_questions:[{id:"q1",question:"How do you develop PM talent on your team? Share a specific example.",type:"textarea"}]
  },
  {
    id:"job-025",title:"Product Manager",
    company:{name:"Zoom",color:"#2D8CFF",initials:"ZM",size:"7,000+",industry:"Video Communications",website:"zoom.us",description:"Zoom is a video communications platform used by 300,000+ business customers worldwide for meetings and collaboration."},
    location:"San Jose, CA",remote:"hybrid",type:"full-time",level:"mid",category:"Product",
    salary:{min:140000,max:190000},posted:"2026-06-18",featured:false,
    excerpt:"Define and ship features for Zoom's core video platform used by 300M+ daily meeting participants.",
    description:"Zoom is looking for a Product Manager to help define the future of video communication and virtual collaboration.",
    responsibilities:["Define requirements and product roadmap for Zoom's core video product","Work with engineering and UX to deliver features on time","Analyze user behavior and research to prioritize features","Manage stakeholder expectations and communicate progress","Define success metrics and track product performance"],
    requirements:["3+ years of product management experience","Experience with consumer or enterprise software","Strong analytical skills","Excellent written and verbal communication","Technical aptitude to work with engineering teams"],
    nice_to_have:["Experience with video or audio technology","Knowledge of WebRTC","Experience with AI features"],
    skills:["Product Management","Analytics","Roadmapping","User Research","Agile","Video Technology"],
    benefits:["RSUs","Health insurance","401k","Flexible hours","Parental leave","Wellness benefits"],
    screening_questions:[{id:"q1",question:"Describe a product decision that required balancing competing stakeholder interests.",type:"textarea"}]
  },
  {
    id:"job-026",title:"Product Manager",
    company:{name:"Loom",color:"#625DF5",initials:"LM",size:"200–500",industry:"Video Messaging",website:"loom.com",description:"Loom is a video messaging tool that helps you get your message across through instantly shareable video."},
    location:"Remote",remote:"remote",type:"full-time",level:"mid",category:"Product",
    salary:{min:130000,max:175000},posted:"2026-06-14",featured:false,
    excerpt:"Shape the product at Loom — async video communication tool loved by teams at 200,000+ companies.",
    description:"Join Loom's product team to shape the future of async video communication. You'll have high ownership and direct impact on a beloved product.",
    responsibilities:["Own the roadmap for a core Loom product area","Define requirements and work with engineering on delivery","Conduct customer interviews and synthesize findings","Analyze product data to identify growth opportunities","Partner with marketing on product launches"],
    requirements:["3+ years of product management experience","Experience in consumer or prosumer SaaS","Strong written communication for async work","Data-driven product instinct","Empathy for the end user"],
    nice_to_have:["Experience with video products","PLG (product-led growth) experience","Remote-first work experience"],
    skills:["Product Management","PLG","Analytics","Customer Research","Async Communication","Roadmapping"],
    benefits:["Equity","Remote-first","Health insurance","Home office budget","Async-first culture","Flexible PTO"],
    screening_questions:[{id:"q1",question:"How do you prioritize features when you have more demand than engineering capacity?",type:"textarea"}]
  },
  // FINANCE
  {
    id:"job-027",title:"Finance Manager",
    company:{name:"Plaid",color:"#374151",initials:"PL",size:"1,000–2,000",industry:"Fintech",website:"plaid.com",description:"Plaid builds the infrastructure that connects apps to users' bank accounts, powering the fintech revolution."},
    location:"San Francisco, CA",remote:"hybrid",type:"full-time",level:"senior",category:"Finance",
    salary:{min:130000,max:175000},posted:"2026-06-25",featured:false,
    excerpt:"Lead financial planning and analysis for Plaid's rapidly growing fintech business.",
    description:"Join Plaid's finance team to manage financial planning, forecasting, and business analysis as the company continues to scale.",
    responsibilities:["Lead annual planning, quarterly forecasting, and monthly close","Build financial models and scenario analyses","Partner with business leaders on strategic decisions","Develop KPI dashboards and financial reporting","Manage and develop a team of 2-3 finance analysts"],
    requirements:["6+ years of finance experience (FP&A or investment banking)","Advanced financial modeling skills","Experience with SQL for data analysis","Strong communication and business partnership skills","CFA or CPA preferred"],
    nice_to_have:["Experience with fintech or payments business models","Investment banking background","Experience with fundraising"],
    skills:["FP&A","Financial Modeling","SQL","Excel","Business Analysis","Budgeting"],
    benefits:["Equity","Health insurance","401k","Learning budget","Flexible PTO","Team events"],
    screening_questions:[{id:"q1",question:"Describe a financial model you built that drove a key business decision.",type:"textarea"}]
  },
  {
    id:"job-028",title:"Financial Analyst",
    company:{name:"Robinhood",color:"#00C805",initials:"RH",size:"3,000+",industry:"Fintech",website:"robinhood.com",description:"Robinhood democratizes finance by providing commission-free stock trading and investing to everyone."},
    location:"Menlo Park, CA",remote:"hybrid",type:"full-time",level:"entry",category:"Finance",
    salary:{min:85000,max:125000},posted:"2026-06-20",featured:false,
    excerpt:"Build financial models and analysis to support Robinhood's mission of democratizing finance for all.",
    description:"Robinhood is looking for a Financial Analyst to support FP&A activities, drive analytical insights, and help grow our financial function.",
    responsibilities:["Build and maintain financial models for business planning","Support monthly close and variance analysis","Prepare board and management presentations","Conduct ad-hoc financial analysis","Track KPIs and business metrics"],
    requirements:["2+ years of financial analysis experience","Strong Excel and financial modeling skills","SQL proficiency","Experience at a tech company or investment bank","Strong analytical and communication skills"],
    nice_to_have:["CFA Level 1 or higher","Experience in fintech","Python skills for financial modeling"],
    skills:["Financial Modeling","Excel","SQL","FP&A","PowerPoint","Analytics"],
    benefits:["RSUs","Health insurance","401k","Free Robinhood Gold","Flexible PTO","Learning budget"],
    screening_questions:[{id:"q1",question:"Describe a time you used data to drive a business decision. What was the outcome?",type:"textarea"}]
  },
  {
    id:"job-029",title:"Senior Accountant",
    company:{name:"Coinbase",color:"#0052FF",initials:"CB",size:"3,000+",industry:"Crypto",website:"coinbase.com",description:"Coinbase is the leading cryptocurrency exchange platform in the United States."},
    location:"San Francisco, CA",remote:"hybrid",type:"full-time",level:"mid",category:"Finance",
    salary:{min:100000,max:145000},posted:"2026-06-16",featured:false,
    excerpt:"Join Coinbase's accounting team and help build the financial foundation for the future of crypto finance.",
    description:"Coinbase is seeking a Senior Accountant to support accounting operations as the company continues to grow at the forefront of the crypto economy.",
    responsibilities:["Manage month-end close and financial reporting","Reconcile crypto asset accounts and transactions","Prepare technical accounting memos for complex transactions","Support external audit and regulatory filings","Identify and implement process improvements"],
    requirements:["4+ years of accounting experience","CPA license (or in progress)","Strong knowledge of US GAAP","Experience with complex financial instruments","Public accounting experience preferred"],
    nice_to_have:["Experience with crypto accounting","Knowledge of blockchain technology","Big 4 public accounting background"],
    skills:["US GAAP","NetSuite","Excel","Financial Reporting","Crypto Accounting","Audit"],
    benefits:["RSUs","Health insurance","401k","Crypto benefits","Learning budget","Remote-friendly"],
    screening_questions:[{id:"q1",question:"What experience do you have with complex financial instruments or non-standard accounting?",type:"textarea"}]
  },
  // DATA
  {
    id:"job-030",title:"Data Scientist",
    company:{name:"Snowflake",color:"#29B5E8",initials:"SW",size:"6,000+",industry:"Cloud Data",website:"snowflake.com",description:"Snowflake delivers the Data Cloud, enabling companies to mobilize their data with limitless scale, performance, and concurrency."},
    location:"San Mateo, CA",remote:"hybrid",type:"full-time",level:"senior",category:"Data",
    salary:{min:155000,max:210000},posted:"2026-06-26",featured:false,
    excerpt:"Drive data science initiatives to optimize Snowflake's product, pricing, and customer success at scale.",
    description:"Join Snowflake's data science team to build predictive models and analytical frameworks that drive product and business decisions.",
    responsibilities:["Build and deploy predictive models for product and business problems","Design and analyze A/B experiments","Develop ML pipelines for production use","Present findings to business stakeholders","Drive self-service analytics capabilities"],
    requirements:["4+ years of data science experience","Strong Python and SQL skills","Experience with ML frameworks (scikit-learn, XGBoost)","Experience with A/B testing and causal inference","Strong statistical knowledge"],
    nice_to_have:["Experience with deep learning frameworks","Knowledge of Snowflake platform","Published research or conference presentations"],
    skills:["Python","SQL","Snowflake","scikit-learn","Statistics","A/B Testing"],
    benefits:["Equity (RSUs)","Health insurance","401k","Remote-friendly","Learning budget","Unlimited PTO"],
    screening_questions:[{id:"q1",question:"Describe an end-to-end ML project you built. What was the business impact?",type:"textarea"}]
  },
  {
    id:"job-031",title:"Analytics Engineer",
    company:{name:"Databricks",color:"#FF3621",initials:"DB",size:"5,000+",industry:"Data & AI",website:"databricks.com",description:"Databricks is the data and AI company, pioneering the open lakehouse architecture for enterprise data teams."},
    location:"San Francisco, CA",remote:"hybrid",type:"full-time",level:"mid",category:"Data",
    salary:{min:140000,max:195000},posted:"2026-06-23",featured:false,
    excerpt:"Build the analytics infrastructure that powers business decisions at one of the fastest-growing data companies.",
    description:"Join Databricks' data team as an Analytics Engineer to build scalable data models and analytics frameworks that power business intelligence.",
    responsibilities:["Build and maintain data models using dbt","Partner with business stakeholders to understand data needs","Ensure data quality and reliability in analytics pipelines","Create documentation and data dictionaries","Build dashboards and self-service analytics tools"],
    requirements:["3+ years of analytics engineering or data experience","Expert SQL skills","Experience with dbt","Strong data modeling skills","Experience with BI tools (Tableau, Looker, or similar)"],
    nice_to_have:["Experience with Databricks platform","Knowledge of Apache Spark","Python skills for custom transformations"],
    skills:["SQL","dbt","Databricks","Data Modeling","Tableau","Python"],
    benefits:["Equity (RSUs)","Health insurance","401k","Unlimited PTO","Learning budget","Team events"],
    screening_questions:[{id:"q1",question:"How do you ensure data quality in an analytics pipeline? What tools and processes do you use?",type:"textarea"}]
  },
  {
    id:"job-032",title:"Data Analyst",
    company:{name:"Amplitude",color:"#1A6BC4",initials:"AM",size:"500–1,000",industry:"Analytics",website:"amplitude.com",description:"Amplitude is the leading digital analytics platform, helping companies build better products through data."},
    location:"San Francisco, CA",remote:"hybrid",type:"full-time",level:"mid",category:"Data",
    salary:{min:110000,max:150000},posted:"2026-06-18",featured:false,
    excerpt:"Use Amplitude's own product to uncover insights that drive product decisions and business growth.",
    description:"Amplitude is looking for a Data Analyst to help us understand how customers use our analytics platform and identify opportunities for growth.",
    responsibilities:["Analyze product usage data to surface actionable insights","Build and maintain dashboards for key business metrics","Partner with product managers on feature prioritization","Design and evaluate A/B experiments","Present data findings to executives and stakeholders"],
    requirements:["3+ years of data analysis experience","Expert SQL skills","Experience with product analytics tools","Strong data visualization skills","Comfort with statistical analysis and experimentation"],
    nice_to_have:["Experience with Amplitude platform","Python or R for statistical analysis","Experience with cohort analysis"],
    skills:["SQL","Amplitude","Tableau","A/B Testing","Data Visualization","Excel"],
    benefits:["Equity","Health insurance","401k","Learning budget","Flexible work","Free Amplitude"],
    screening_questions:[{id:"q1",question:"Describe an analysis you performed that changed a product decision. What did you find?",type:"textarea"}]
  },
  // HR
  {
    id:"job-033",title:"HR Business Partner",
    company:{name:"Gusto",color:"#F9547E",initials:"GU",size:"2,000+",industry:"HR & Payroll",website:"gusto.com",description:"Gusto helps small businesses take care of their teams with payroll, benefits, and HR tools."},
    location:"San Francisco, CA",remote:"hybrid",type:"full-time",level:"mid",category:"HR",
    salary:{min:100000,max:140000},posted:"2026-06-22",featured:false,
    excerpt:"Partner with engineering and product leaders at Gusto to build a high-performing, inclusive team culture.",
    description:"Gusto is seeking an HR Business Partner to work closely with our engineering and product organizations, supporting leadership with people strategy and talent development.",
    responsibilities:["Partner with senior leaders on people strategy and organizational design","Manage employee relations issues with empathy and expertise","Drive performance management and talent review cycles","Support leadership development and coaching","Lead diversity, equity, and inclusion initiatives"],
    requirements:["4+ years of HR business partner experience","Experience supporting engineering or technical organizations","Strong employment law knowledge","Proven track record in employee relations","Experience with performance management systems"],
    nice_to_have:["HR certifications (PHR, SHRM-CP)","Experience at high-growth tech startups","DEI program management experience"],
    skills:["HR Business Partnering","Employee Relations","Performance Management","DEI","Talent Development","Workday"],
    benefits:["Equity","Health insurance","401k","Parental leave","Mental health benefits","Flexible PTO"],
    screening_questions:[{id:"q1",question:"Describe a complex employee relations situation you managed. How did you approach it?",type:"textarea"}]
  },
  {
    id:"job-034",title:"Talent Acquisition Specialist",
    company:{name:"Lattice",color:"#7B68EE",initials:"LA",size:"500–1,000",industry:"People Management",website:"lattice.com",description:"Lattice is a people management platform that helps HR leaders build engaged, high-performing teams."},
    location:"Remote",remote:"remote",type:"full-time",level:"mid",category:"HR",
    salary:{min:80000,max:115000},posted:"2026-06-14",featured:false,
    excerpt:"Help Lattice hire world-class talent by managing full-cycle recruiting for engineering and product roles.",
    description:"Lattice is looking for a Talent Acquisition Specialist to help us build our team by identifying, attracting, and hiring exceptional candidates.",
    responsibilities:["Manage full-cycle recruiting for engineering and product roles","Source passive candidates through LinkedIn, GitHub, and events","Partner with hiring managers on job requirements and evaluation criteria","Drive DEI initiatives in the recruiting process","Provide exceptional candidate experience throughout the process"],
    requirements:["3+ years of full-cycle recruiting experience","Experience recruiting for technical roles (engineering, product, design)","Proficiency with Greenhouse or similar ATS","Strong sourcing skills and creative approach","Data-driven recruiting approach"],
    nice_to_have:["Experience with employer branding","Knowledge of technical skills for engineering evaluation","DEI recruiting certifications"],
    skills:["Full-Cycle Recruiting","Sourcing","Greenhouse","LinkedIn Recruiter","Technical Recruiting","DEI"],
    benefits:["Equity","Remote-first","Health insurance","401k","Learning budget","Flexible PTO"],
    screening_questions:[{id:"q1",question:"How do you approach sourcing for hard-to-fill technical roles?",type:"textarea"}]
  },
  // OPERATIONS
  {
    id:"job-035",title:"Operations Manager",
    company:{name:"DoorDash",color:"#FF3008",initials:"DD",size:"15,000+",industry:"Food Delivery",website:"doordash.com",description:"DoorDash is America's largest food delivery platform, connecting customers with restaurants in 7,000+ cities."},
    location:"San Francisco, CA",remote:"hybrid",type:"full-time",level:"mid",category:"Operations",
    salary:{min:100000,max:140000},posted:"2026-06-20",featured:false,
    excerpt:"Drive operational excellence for DoorDash's marketplace — optimizing the experience for customers, merchants, and Dashers.",
    description:"Join DoorDash's operations team to improve the efficiency and quality of our marketplace operations, helping millions of customers get their food fast.",
    responsibilities:["Manage day-to-day marketplace operations for a key market","Analyze operational data to identify inefficiencies","Develop and implement process improvements","Build relationships with restaurant partners","Lead cross-functional projects with product and engineering"],
    requirements:["3+ years of operations or strategy experience","Strong analytical skills and SQL proficiency","Experience in marketplace or logistics businesses","Proven project management skills","Comfort with ambiguity and fast-paced environments"],
    nice_to_have:["MBA or consulting background","Experience in food delivery or on-demand marketplace","Python skills for operational analytics"],
    skills:["Operations Management","SQL","Project Management","Analytics","Process Improvement","Stakeholder Management"],
    benefits:["Equity (RSUs)","Health insurance","401k","DashPass","Learning budget","Flexible PTO"],
    screening_questions:[{id:"q1",question:"Describe a process you improved that had measurable impact. What was your approach?",type:"textarea"}]
  },
  {
    id:"job-036",title:"Supply Chain Manager",
    company:{name:"Instacart",color:"#43B02A",initials:"IC",size:"3,000+",industry:"Grocery Delivery",website:"instacart.com",description:"Instacart is the leading grocery technology company in North America, partnering with 1,400+ retailers."},
    location:"San Francisco, CA",remote:"onsite",type:"full-time",level:"mid",category:"Operations",
    salary:{min:110000,max:155000},posted:"2026-06-17",featured:false,
    excerpt:"Optimize Instacart's supply chain to ensure grocery delivery to customers in under 2 hours across North America.",
    description:"Instacart is seeking a Supply Chain Manager to optimize grocery delivery operations and ensure we meet our customer promise of fast, accurate delivery.",
    responsibilities:["Manage supplier relationships and inventory allocation","Develop demand forecasting models","Optimize delivery routing and logistics networks","Identify and resolve supply chain disruptions","Report on supply chain performance metrics"],
    requirements:["4+ years of supply chain management experience","Experience with forecasting and inventory optimization","Strong analytical skills and SQL proficiency","Experience with supply chain software (SAP, Oracle)","Bachelor's in supply chain, operations, or engineering"],
    nice_to_have:["APICS certification (CSCP, CPIM)","Experience in grocery or e-commerce","Python skills for supply chain modeling"],
    skills:["Supply Chain","Forecasting","SQL","Logistics","Inventory Management","Project Management"],
    benefits:["RSUs","Health insurance","401k","Grocery credits","Flexible PTO","Parental leave"],
    screening_questions:[{id:"q1",question:"Describe a supply chain challenge you faced and how you solved it.",type:"textarea"}]
  },
  // SALES
  {
    id:"job-037",title:"Enterprise Account Executive",
    company:{name:"Salesforce",color:"#00A1E0",initials:"SF2",size:"70,000+",industry:"CRM & Cloud",website:"salesforce.com",description:"Salesforce is the world's #1 CRM, helping companies of every size connect with their customers."},
    location:"New York, NY",remote:"hybrid",type:"full-time",level:"senior",category:"Sales",
    salary:{min:120000,max:200000},posted:"2026-06-28",featured:false,
    excerpt:"Drive enterprise sales for Salesforce's CRM platform, closing 7-figure deals with Fortune 500 companies.",
    description:"Salesforce is looking for an Enterprise Account Executive to sell our CRM platform to large enterprise customers, driving revenue growth through strategic relationships.",
    responsibilities:["Own a portfolio of 20-30 enterprise accounts","Drive net-new revenue through prospecting and relationship building","Navigate complex enterprise sales cycles (6-12 months)","Collaborate with solution engineers on technical proposals","Exceed quarterly and annual revenue quotas"],
    requirements:["5+ years of enterprise SaaS sales experience","Proven track record of exceeding quota","Experience selling to C-suite executives","Strong negotiation and closing skills","Experience with complex, multi-stakeholder deals"],
    nice_to_have:["Experience selling Salesforce products","Vertical expertise (financial services, healthcare)","Salesforce certifications","MEDDPICC sales methodology experience"],
    skills:["Enterprise Sales","CRM","Salesforce","Negotiation","Account Management","Solution Selling"],
    benefits:["Competitive base + commission","RSUs","Health insurance","401k","President's Club","Career development"],
    screening_questions:[{id:"q1",question:"Tell us about the largest deal you've closed. What was the sales cycle and how did you win it?",type:"textarea"},{id:"q2",question:"What is your average quota attainment over the last 3 years?",type:"select",options:["<80%","80-100%","100-120%",">120%"]}]
  }
];

// ---- Helpers ----
const CATEGORIES = [...new Set(JOBS_DATA.map(j => j.category))].sort();
const JOB_TYPES  = [...new Set(JOBS_DATA.map(j => j.type))];
const LEVELS     = [...new Set(JOBS_DATA.map(j => j.level))];
const REMOTES    = [...new Set(JOBS_DATA.map(j => j.remote))];

function getFeaturedJobs()          { return JOBS_DATA.filter(j => j.featured); }
function getJobById(id)             { return JOBS_DATA.find(j => j.id === id) || null; }
function getSimilarJobs(jobId, n=3) {
  const job = getJobById(jobId);
  if (!job) return [];
  return JOBS_DATA.filter(j => j.id !== jobId && j.category === job.category).slice(0, n);
}
